name = "careos"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "doctor-db"
database_id = "590a6ede-a027-4b9a-ab4a-41a90f607a2b"

[[r2_buckets]]
binding = "R2"
bucket_name = "doctor-media"
